In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([(1.5,2,3), (4,5,6)]),
print(b)

(array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]]),)


In [4]:
 c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]]),
print(c)

(array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]]),)


In [5]:
np.save("my_array", a)

In [6]:
np.savez('array.npz', a, b)

In [7]:
np.load('my_array.npy')

array([1, 2, 3])

In [10]:
np.save("myfile.txt", a)

In [9]:
np.load("myfile.txt.npy")

array([1, 2, 3])

In [11]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [12]:
a.shape

(3,)

In [13]:
len(a)

3

In [13]:
len(a)

3

In [13]:
len(a)

3

In [16]:
 g = a - b

In [17]:
print(g)

[[[-0.5  0.   0. ]
  [-3.  -3.  -3. ]]]


In [18]:
h = a + b
print(h)

[[[2.5 4.  6. ]
  [5.  7.  9. ]]]


In [19]:
w = a * b
print(w)

[[[ 1.5  4.   9. ]
  [ 4.  10.  18. ]]]
